@mcp_client_HostAddress = https://localhost:7005

POST {{mcp_client_HostAddress}}/chat/ask
Content-Type: application/json

{
  "Text" : "how is the weather in london today ?" 
}

###

POST {{mcp_client_HostAddress}}/chat/ask-mcp
Content-Type: application/json

{
  "Text" : "how is the weather in london today ?" 
}

###

GET {{mcp_client_HostAddress}}/chat/resources

###

@resource=file%3A%2F%2F%2Fc%3A%2FTemp
GET {{mcp_client_HostAddress}}/chat/resource?name={{resource}}

###
