@mcp_client_sk_HostAddress = https://localhost:7244
@conversationId = 5a61c454-6f48-4814-afb0-3cac6ce295ad
POST {{mcp_client_sk_HostAddress}}/chat/ask
Content-Type: application/json

{
  
  "conversationId": "{{conversationId}}",
  "UserPrompt" : "how is the weather in london today ?"
}

###

POST {{mcp_client_sk_HostAddress}}/chat/ask
Content-Type: application/json

{
  
  "conversationId": "{{conversationId}}",
  "UserPrompt" : "and what about turin?"
}


###
