@weathermcpserver_dapr_HostAddress = http://localhost:5062
@weathermcpserver_dapr_HostAddress_dapr = http://localhost:3500

@location=london
POST {{weathermcpserver_dapr_HostAddress}}/weatherforecast/get-weather
Content-Type: application/json

{
  "location": "{{location}}"
}

###

GET {{weathermcpserver_dapr_HostAddress}}/currentweather/get-computer-name

###


GET {{weathermcpserver_dapr_HostAddress_dapr}}/currentweather/get-computer-name
dapr-app-id: weathermcpserver_dapr